### ISSUE TITLE
Настроить CORS

### ISSUE THREAD

**Issue by OkciD** [frontend-park-mail-ru/2017_2_JeEs#3]
Необходимо настроить CORS в модуле Http.js, чтобы обращаться к беку на другом домене.

**Comment by ostapenko-me** [comment]
Ребят, про это будет в следующей лекции, если что. Там будет всё подробно объясняться ;)

**Comment by barzug** [comment]
Мы будем рады послушать, но за это в четверг 5 баллов ставится)

**Comment by avtyul** [comment]
с - согласованные программы курсов

**Comment by ostapenko-me** [comment]
Причём на самом курсе джавы про корс было сказано только
> Используйте `@CrossOrigin`

I Like It!
